(() => {
const tasks=[{name:"Singkirkan distraksi",hint:"Taruh HP di luar jangkauan, atau tutup satu tab yang mengganggu.",icon:"phone",steps:["Pilih satu gangguan di dekatmu.","Jauhkan atau tutup sekarang.","Kembali ke satu hal yang ingin dikerjakan."]},{name:"Siapkan tempat mulai",hint:"Rapikan satu bagian meja dan siapkan alat yang dibutuhkan.",icon:"desk",steps:["Lihat tempat kamu akan bekerja.","Geser benda yang tidak diperlukan.","Sisakan alat untuk satu pekerjaan."]},{name:"Mulai tugas tertunda",hint:"Buka tugasnya. Kerjakan bagian paling kecil selama satu menit.",icon:"play",steps:["Pilih satu tugas di pikiranmu.","Buka file, buku, atau alatnya.","Kerjakan bagian terkecil. Tidak harus langsung tuntas."]}];
const root=document.createElement("section");root.className="motion-framework";root.setAttribute("aria-label","Panduan aksi tanpa mengetik");document.querySelector(".notes").before(root);
const oldNotes=document.querySelector(".notes");const notes=document.createElement("details");notes.className="optional-notes";const summary=document.createElement("summary");summary.textContent="Catatan tambahan (opsional)";oldNotes.before(notes);notes.append(summary,oldNotes);
const style=document.createElement("style");style.textContent=`.motion-framework{margin:28px 0;border:1px solid #d7d7cb;border-radius:18px;background:#fffcf5;overflow:hidden}.mf-head{padding:24px 24px 0}.mf-head h2{margin:8px 0}.mf-track{display:flex;align-items:center;gap:8px;padding:18px 24px;font-size:12px;color:#575d51}.mf-track span{padding:7px 10px;border-radius:20px}.mf-track .active{background:#28392c;color:white}.mf-track i{flex:1;height:1px;background:#c3c8b9}.mf-stage{padding:0 24px 24px}.mf-choices{display:grid;gap:10px}.mf-choice{text-align:left;width:100%;display:flex;gap:14px;align-items:center;padding:16px!important;white-space:normal}.mf-choice strong{display:block;font-size:15px}.mf-choice small{display:block;color:#555d50;font-size:13px;line-height:1.6;margin-top:4px}.mf-choice b{font-size:24px;font-weight:400;color:#985132}.mf-scene{height:180px;position:relative;display:grid;place-items:center;background:#ecefe4;border-radius:12px;margin:8px 0 20px;overflow:hidden}.mf-orbit{position:absolute;width:140px;height:140px;border:1px solid #b4c1a5;border-radius:50%;animation:mfPulse 3s ease-in-out infinite}.mf-orbit:nth-child(2){width:100px;height:100px;animation-delay:1s}.mf-object{width:50px;height:82px;border:3px solid #334a36;border-radius:9px;background:#fbfcf5;display:grid;place-items:center;font-size:26px;z-index:1;animation:mfMove 3s ease-in-out infinite}.mf-scene.desk .mf-object{width:112px;height:55px;border-radius:4px;transform:rotate(-5deg)}.mf-scene.play .mf-object{width:80px;height:80px;border-radius:50%}.mf-scene.done .mf-object{width:80px;height:80px;border-radius:50%;background:#334a36;color:white;animation:mfPop .5s ease-out}.mf-directions{list-style:none;padding:0;counter-reset:step}.mf-directions li{display:flex;gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid #dedfd4;font-size:14px;line-height:1.5}.mf-directions li:before{counter-increment:step;content:counter(step);display:grid;place-items:center;flex:0 0 28px;height:28px;border-radius:50%;background:#e6ebdc;color:#334a36}.mf-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.mf-clock{font-size:46px;font-variant-numeric:tabular-nums;margin:14px 0}.mf-hint{font-size:13px;color:#575d51;line-height:1.6}.mf-foot{padding:0 24px 20px;font-size:12px;color:#636958}.optional-notes{margin:20px 0}.optional-notes>summary{cursor:pointer;padding:14px 0;min-height:44px}.mf-stage:focus{outline:none}@keyframes mfMove{0%,100%{translate:0 0;rotate:-4deg}50%{translate:15px -7px;rotate:6deg}}@keyframes mfPulse{50%{scale:1.12;opacity:.4}}@keyframes mfPop{from{scale:.7;opacity:0}to{scale:1;opacity:1}}@media(max-width:420px){.mf-head{padding:18px 16px 0}.mf-stage{padding:0 16px 18px}.mf-track{padding:16px}.mf-foot{padding:0 16px 18px}.mf-actions button{flex:1}.mf-scene{height:160px}}@media(prefers-reduced-motion:reduce){.motion-framework *{animation:none!important;transition:none!important}}`;
document.head.append(style);
function data(){if(!state.quickActions||typeof state.quickActions!=="object")state.quickActions={};if(!state.quickActions[LESSON])state.quickActions[LESSON]={selected:null,phase:"choose",left:60,deadline:null};return state.quickActions[LESSON];}
function store(){const ok=save();const label=root.querySelector(".mf-foot");if(label)label.textContent=ok?"Panduan praktik umum, bukan framework resmi video. Progres tersimpan di browser.":"Belum tersimpan. Browser menolak penyimpanan; unduh cadangan.";}
function seconds(){const s=data();return s.deadline?Math.max(0,Math.ceil((s.deadline-Date.now())/1000)):s.left;}
function scene(task,done=false){return `<div class="mf-scene ${done?"done":task.icon}" aria-hidden="true"><div class="mf-orbit"></div><div class="mf-orbit"></div><div class="mf-object">${done?"✓":task.icon==="play"?"▶":task.icon==="desk"?"▤":"·"}</div></div>`;}
function render(focus=false){const s=data();if(!tasks[s.selected]&&s.phase!=="choose")s.phase="choose";const task=tasks[s.selected];root.innerHTML=`<div class="mf-head"><div class="eyebrow">Pahami → mulai → ulangi</div><h2>Jangan cuma ditonton.</h2><p class="mf-hint">Tidak perlu menulis. Pilih, lakukan, lalu tap selesai.</p></div><div class="mf-track" aria-label="Alur praktik"><span class="${s.phase==="choose"?"active":""}">1 · Pilih</span><i></i><span class="${s.phase==="do"?"active":""}">2 · Lakukan</span><i></i><span class="${s.phase==="done"?"active":""}">3 · Selesai</span></div><div class="mf-stage" tabindex="-1"></div><div class="mf-foot"></div>`;const box=root.querySelector(".mf-stage");
if(s.phase==="choose"){box.innerHTML=`<div class="mf-choices">${tasks.map((t,i)=>`<button class="mf-choice" data-task="${i}"><b aria-hidden="true">0${i+1}</b><span><strong>${t.name}</strong><small>${t.hint}</small></span></button>`).join("")}</div>`;box.querySelectorAll("[data-task]").forEach(b=>b.onclick=()=>{s.selected=Number(b.dataset.task);s.phase="do";s.left=60;s.deadline=null;store();render(true);});}
else if(s.phase==="do"){box.innerHTML=scene(task)+`<h3>${task.name}</h3><ol class="mf-directions">${task.steps.map(t=>`<li>${t}</li>`).join("")}</ol><div class="mf-clock" aria-label="Sisa waktu latihan">01:00</div><p class="mf-hint" id="mfTimeHint">Satu menit untuk mulai. Timer opsional, bukan syarat selesai.</p><div class="mf-actions"><button id="mfTimer">${s.deadline?"Jeda timer":"Mulai 1 menit"}</button><button id="mfDone" class="primary">Sudah kulakukan ✓</button><button id="mfBack">Ganti aksi</button></div>`;box.querySelector("#mfTimer").onclick=()=>{if(s.deadline){s.left=seconds();s.deadline=null;}else{s.left=seconds()||60;s.deadline=Date.now()+s.left*1000;}store();render();};box.querySelector("#mfDone").onclick=()=>{s.phase="done";s.deadline=null;s.completedAt=new Date().toISOString();store();render(true);};box.querySelector("#mfBack").onclick=()=>{s.phase="choose";s.deadline=null;store();render(true);};tick();}
else{box.innerHTML=scene(task,true)+`<h3>Satu aksi sudah kamu lakukan.</h3><p class="mf-hint">${task.name}. Yang dihitung bukan mengisi formulir, tapi mulai bergerak.</p><p class="mf-hint">Dicatat berdasarkan konfirmasimu. Checklist video tidak berubah.</p><div class="mf-actions"><button id="mfAgain">Pilih aksi lain</button></div>`;box.querySelector("#mfAgain").onclick=()=>{s.phase="choose";store();render(true);};}
store();if(focus){box.focus({preventScroll:true});root.scrollIntoView({block:"nearest",behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth"});}if(!matchMedia("(prefers-reduced-motion: reduce)").matches)box.animate([{opacity:0,transform:"translateY(8px)"},{opacity:1,transform:"translateY(0)"}],{duration:250,easing:"ease-out"});}
function tick(){const s=data(), clock=root.querySelector(".mf-clock");if(!clock)return;const n=seconds();clock.textContent="0"+Math.floor(n/60)+":"+String(n%60).padStart(2,"0");if(n===0){root.querySelector("#mfTimeHint").textContent="Satu menit lewat. Sudah dilakukan? Tap konfirmasi jika sudah.";if(s.deadline){s.deadline=null;s.left=0;root.querySelector("#mfTimer").textContent="Ulangi 1 menit";store();}}}
const previousImport=document.getElementById("importFile").onchange;document.getElementById("importFile").onchange=async e=>{const file=e.target.files[0];document.getElementById("backupStatus").textContent="";await previousImport(e);if(file&&document.getElementById("backupStatus").textContent==="Cadangan berhasil dipulihkan."){try{const incoming=JSON.parse(await file.text()).state.quickActions;if(incoming&&typeof incoming==="object"&&!Array.isArray(incoming)){state.quickActions={...state.quickActions,...incoming};render();}}catch{}}};
render();setInterval(tick,1000);document.addEventListener("visibilitychange",()=>{if(!document.hidden)tick();});
})();

document.getElementById("closeCelebrate").textContent="Langsung praktik";document.getElementById("closeCelebrate").onclick=()=>{document.getElementById("celebrate").close();document.querySelector(".motion-framework").scrollIntoView({block:"start"});document.querySelector(".mf-stage button")?.focus({preventScroll:true});};
